name : CI dbt
on :
  push :
    branches :
     - main
  workflow_dispatch :

env : 
    SNOWFLAKE_ACCOUNT : ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SNOWFLAKE_USER : ${{ secrets.SNOWFLAKE_USER }}
    SNOWFLAKE_PASSWORD : ${{ secrets.SNOWFLAKE_PASSWORD }}
    SNOWFLAKE_ROLE : ${{ secrets.SNOWFLAKE_ROLE }}
    SNOWFLAKE_SCHEMA : ${{ secrets.SNOWFLAKE_SCHEMA }}

jobs :
  dbt_ci :
    runs-on : ubuntu-latest
    defaults :
     run :
      working-directory : ./dbt
    steps :
      - name : checkout repo
        uses : actions/checkout@v4
      - name : install dependencies
        run : pip install dbt-core dbt-snowflake 
      - name : install dbt packages
        run : dbt deps 
      - name : run tests 
        run : dbt test --profiles-dir .
      - name : run the models 
        run : dbt run --profiles-dir .
         
